services:
  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    ports:
      - "7700:7700"
    volumes:
      - ./BACKEND:/app

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./FRONTEND:/app
